# Program title: Storytelling App
# ISOM5240 Individual Assignment
# This app turns an uploaded image into a short children's story and audio.

# -----------------------------
# Import part
# -----------------------------
import streamlit as st
from transformers import pipeline
from PIL import Image
import tempfile
import os
import re


# -----------------------------
# Model loading part
# -----------------------------

@st.cache_resource
def load_img2text_model():
    """
    Load the image-to-text model from Hugging Face.
    This model generates a caption based on the uploaded image.
    """
    return pipeline(
        "image-to-text",
        model="Salesforce/blip-image-captioning-base"
    )


@st.cache_resource
def load_story_model():
    """
    Load a Hugging Face text generation model.
    FLAN-T5-base is used because it follows instructions better than GPT-2 style models.
    """
    return pipeline(
        "text2text-generation",
        model="google/flan-t5-base"
    )


@st.cache_resource
def load_audio_model():
    """
    Load the text-to-audio model from Hugging Face.
    This model converts the generated story into speech.
    """
    return pipeline(
        "text-to-audio",
        model="Matthijs/mms-tts-eng"
    )


# -----------------------------
# Function part
# -----------------------------

def img2text(image_path):
    """
    Convert an uploaded image into a text description.
    """
    image_to_text_model = load_img2text_model()
    text = image_to_text_model(image_path)[0]["generated_text"]
    return text


def clean_story(story_text):
    """
    Clean prompt leakage, repeated labels, and extra spaces.
    """
    story_text = story_text.strip()

    unwanted_phrases = [
        "Story:",
        "Image description:",
        "Description:",
        "Write a story",
        "Write a short story",
        "The story should",
        "50 to 100 words",
        "60 to 100 words",
        "children aged 3 to 10"
    ]

    for phrase in unwanted_phrases:
        story_text = story_text.replace(phrase, "")

    story_text = re.sub(r"\s+", " ", story_text).strip()
    return story_text


def remove_repeated_sentences(story_text):
    """
    Remove repeated sentences from model output.
    """
    sentences = re.split(r"(?<=[.!?])\s+", story_text)
    unique_sentences = []
    seen = set()

    for sentence in sentences:
        sentence = sentence.strip()
        key = sentence.lower()

        if sentence and key not in seen:
            unique_sentences.append(sentence)
            seen.add(key)

    return " ".join(unique_sentences)


def text2story(text):
    """
    Generate a short children's story based on the image caption.
    The story is generated by a Hugging Face model.
    """
    story_pipe = load_story_model()

    prompt = (
        f"Write a complete children's bedtime story based on this scene: {text}. "
        f"The story must include the main subject from the scene. "
        f"Use simple and warm English. "
        f"Make the story imaginative, gentle, and suitable for young children. "
        f"Do not repeat sentences. "
        f"Do not mention the instruction. "
        f"Write 6 sentences. "
        f"Return only the story."
    )

    story_output = story_pipe(
        prompt,
        min_new_tokens=75,
        max_new_tokens=140,
        num_beams=5,
        repetition_penalty=2.5,
        no_repeat_ngram_size=4,
        early_stopping=True
    )

    story_text = story_output[0]["generated_text"]
    story_text = clean_story(story_text)
    story_text = remove_repeated_sentences(story_text)

    # If the generated story is still too short, ask the model to expand it.
    if len(story_text.split()) < 50:
        expand_prompt = (
            f"Expand this into a complete 6-sentence bedtime story for young children. "
            f"The story must stay based on this scene: {text}. "
            f"Current story: {story_text}. "
            f"Use simple, warm, and imaginative English. "
            f"Return only the expanded story."
        )

        expanded_output = story_pipe(
            expand_prompt,
            min_new_tokens=80,
            max_new_tokens=150,
            num_beams=5,
            repetition_penalty=2.5,
            no_repeat_ngram_size=4,
            early_stopping=True
        )

        story_text = expanded_output[0]["generated_text"]
        story_text = clean_story(story_text)
        story_text = remove_repeated_sentences(story_text)

    # Final safety check: limit to about 100 words
    words = story_text.split()
    if len(words) > 110:
        story_text = " ".join(words[:110]) + "."

    return story_text


def text2audio(story_text):
    """
    Convert the generated story into audio data.
    """
    audio_pipe = load_audio_model()
    audio_data = audio_pipe(story_text)
    return audio_data


# -----------------------------
# Main part
# -----------------------------

st.set_page_config(
    page_title="Your Image to Audio Story",
    page_icon="📖",
    layout="centered"
)

st.title("📖 Turn Your Image to Audio Story")

st.write(
    "Upload an image, and this app will generate a short children's story and read it aloud."
)

uploaded_file = st.file_uploader(
    "Select an image...",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    # Save uploaded image locally as a temporary file
    bytes_data = uploaded_file.getvalue()

    with tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as temp_file:
        temp_file.write(bytes_data)
        image_path = temp_file.name

    # Display uploaded image
    image = Image.open(image_path)
    st.image(image, caption="Uploaded Image", use_container_width=True)

    if st.button("Generate Story"):

        # Stage 1: Image to Text
        st.text("Processing image to text...")
        scenario = img2text(image_path)
        st.write(f"**Description:** {scenario}")

        # Stage 2: Text to Story
        st.text("Generating a story...")
        story = text2story(scenario)
        st.write(f"**Story:** {story}")

        # Stage 3: Story to Audio
        st.text("Generating audio data...")
        audio_data = text2audio(story)

        # Play audio directly using Streamlit
        audio_array = audio_data["audio"]
        sample_rate = audio_data["sampling_rate"]
        st.audio(audio_array, sample_rate=sample_rate)

    # Remove temporary image file
    if os.path.exists(image_path):
        os.remove(image_path)
