# Program title: Storytelling App
# ISOM5240 Individual Assignment
# This app turns an uploaded image into a short children's story and audio.

# -----------------------------
# Import part
# -----------------------------
import streamlit as st
from transformers import pipeline
from PIL import Image
import tempfile
import os
import re


# -----------------------------
# Model loading part
# -----------------------------

@st.cache_resource
def load_img2text_model():
    """
    Load the image-to-text model from Hugging Face.
    This model generates a caption based on the uploaded image.
    """
    return pipeline(
        "image-to-text",
        model="Salesforce/blip-image-captioning-base"
    )


@st.cache_resource
def load_story_model():
    """
    Load a Hugging Face text-to-text generation model.
    FLAN-T5 is used because it follows instructions better than distilgpt2.
    """
    return pipeline(
        "text2text-generation",
        model="google/flan-t5-base"
    )


@st.cache_resource
def load_audio_model():
    """
    Load the text-to-audio model from Hugging Face.
    This model converts the generated story into speech.
    """
    return pipeline(
        "text-to-audio",
        model="Matthijs/mms-tts-eng"
    )


# -----------------------------
# Function part
# -----------------------------

def img2text(image_path):
    """
    Convert an uploaded image into a text description.
    """
    image_to_text_model = load_img2text_model()
    text = image_to_text_model(image_path)[0]["generated_text"]
    return text


def clean_generated_story(story_text):
    """
    Clean repeated phrases, prompt leakage, and unnecessary formatting.
    """
    story_text = story_text.strip()

    # Remove common instruction leakage
    unwanted_phrases = [
        "Write a short story",
        "Write a children's story",
        "The story should",
        "Image description:",
        "Scene:",
        "Story:",
        "Title:",
        "50 to 100 words",
        "60 to 90 words"
    ]

    for phrase in unwanted_phrases:
        story_text = story_text.replace(phrase, "")

    # Remove extra spaces
    story_text = re.sub(r"\s+", " ", story_text).strip()

    return story_text


def remove_repeated_sentences(story_text):
    """
    Remove repeated sentences while keeping the story readable.
    """
    sentences = re.split(r"(?<=[.!?])\s+", story_text)
    unique_sentences = []
    seen = set()

    for sentence in sentences:
        sentence_clean = sentence.strip()
        sentence_key = sentence_clean.lower()

        if sentence_clean and sentence_key not in seen:
            unique_sentences.append(sentence_clean)
            seen.add(sentence_key)

    return " ".join(unique_sentences)


def text2story(text):
    """
    Generate a short children's story based on the image caption.
    The story is generated by a Hugging Face model, not hard-coded.
    """
    story_pipe = load_story_model()

    prompt = (
        f"Create a short, warm, and imaginative bedtime story for children aged 3 to 10. "
        f"The story must be based only on this image description: '{text}'. "
        f"The main subject in the description must appear in the story. "
        f"Do not add unrelated facts, school information, celebrities, movies, or family background. "
        f"Use simple English. Return only the story. "
        f"The story should be about 60 to 90 words."
    )

    story_output = story_pipe(
        prompt,
        max_new_tokens=140,
        num_beams=4,
        repetition_penalty=2.0,
        no_repeat_ngram_size=4,
        early_stopping=True
    )

    story_text = story_output[0]["generated_text"]
    story_text = clean_generated_story(story_text)
    story_text = remove_repeated_sentences(story_text)

    # If the first result is too short, ask the model again with a simpler prompt.
    if len(story_text.split()) < 40:
        second_prompt = (
            f"Based on this scene: '{text}', write one simple children's story. "
            f"Use 5 to 6 sentences. Make it gentle, magical, and suitable for young children. "
            f"Return only the story."
        )

        second_output = story_pipe(
            second_prompt,
            max_new_tokens=140,
            num_beams=4,
            repetition_penalty=2.0,
            no_repeat_ngram_size=4,
            early_stopping=True
        )

        story_text = second_output[0]["generated_text"]
        story_text = clean_generated_story(story_text)
        story_text = remove_repeated_sentences(story_text)

    # Final length control
    words = story_text.split()
    if len(words) > 110:
        story_text = " ".join(words[:110]) + "."

    return story_text


def text2audio(story_text):
    """
    Convert the generated story into audio data.
    """
    audio_pipe = load_audio_model()
    audio_data = audio_pipe(story_text)
    return audio_data


# -----------------------------
# Main part
# -----------------------------

st.set_page_config(
    page_title="Your Image to Audio Story",
    page_icon="📖",
    layout="centered"
)

st.title("📖 Turn Your Image to Audio Story")

st.write(
    "Upload an image, and this app will generate a short children's story and read it aloud."
)

uploaded_file = st.file_uploader(
    "Select an image...",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    # Save uploaded image locally as a temporary file
    bytes_data = uploaded_file.getvalue()

    with tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as temp_file:
        temp_file.write(bytes_data)
        image_path = temp_file.name

    # Display uploaded image
    image = Image.open(image_path)
    st.image(image, caption="Uploaded Image", use_container_width=True)

    if st.button("Generate Story"):

        # Stage 1: Image to Text
        st.text("Processing image to text...")
        scenario = img2text(image_path)
        st.write(f"**Description:** {scenario}")

        # Stage 2: Text to Story
        st.text("Generating a story...")
        story = text2story(scenario)
        st.write(f"**Story:** {story}")

        # Stage 3: Story to Audio
        st.text("Generating audio data...")
        audio_data = text2audio(story)

        # Play audio directly using Streamlit
        audio_array = audio_data["audio"]
        sample_rate = audio_data["sampling_rate"]
        st.audio(audio_array, sample_rate=sample_rate)

    # Remove temporary image file
    if os.path.exists(image_path):
        os.remove(image_path)
